# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: steffenlem-sradownloader-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::sra-tools=2.10.8
  - conda-forge::pigz=2.3.4
  - conda-forge::click=7.1.1
  - conda-forge::markdown=3.1.1
  - conda-forge::shortuuid=1.0.1

