# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-sradownloader-0.1dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::sra-tools=2.10.3
  - conda-forge::pigz=2.3.4
  - conda-forge::click=7.1.1
  - conda-forge::markdown=3.2.1

